"""
RAGAS-Inspired Automated Evaluation Script

This script implements automated RAG evaluation metrics inspired by the RAGAS framework:
- Context Relevancy: How relevant is the retrieved employee data to the CV generation task?
- Answer Relevancy: How relevant is the generated CV to the source data?
- Faithfulness: Does the CV contain only information from the source (no hallucinations)?
- Completeness: Does the CV include all critical information from the source?

References:
- https://docs.ragas.io/en/latest/concepts/metrics/index.html
- https://www.confident-ai.com/blog/a-complete-guide-to-rag-evaluation
"""

import json
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from typing import List, Dict
from pydantic import BaseModel
from lib.llm import get_llm_response, get_model_for_task
from services.rag_faiss import merge_records_on_the_fly, build_index
from services.agents import DraftingAgent


class EvaluationMetrics(BaseModel):
    """Structured evaluation metrics for a single CV generation."""
    context_relevancy: float  # 0-1: How relevant is source data to CV task
    answer_relevancy: float   # 0-1: How relevant is CV to source data
    faithfulness: float       # 0-1: No hallucinations (all info from source)
    completeness: float       # 0-1: All critical info included
    overall_score: float      # 0-10: Holistic quality
    reasoning: str            # Explanation of scores


class RAGASEvaluationReport(BaseModel):
    """Full evaluation report with metrics for multiple CVs."""
    evaluations: List[EvaluationMetrics]
    average_context_relevancy: float
    average_answer_relevancy: float
    average_faithfulness: float
    average_completeness: float
    average_overall_score: float


def evaluate_cv_with_ragas(source_data: Dict, generated_cv: Dict) -> EvaluationMetrics:
    """
    Evaluate a single CV using RAGAS-inspired metrics.
    
    Args:
        source_data: Original employee record from RAG system
        generated_cv: CV generated by DraftingAgent
    
    Returns:
        EvaluationMetrics with scores and reasoning
    """
    system_prompt = """You are an expert evaluator for RAG-based CV generation systems.
    Evaluate the generated CV against the source employee data using these metrics:
    
    1. context_relevancy (0-1): Is the source data relevant for CV generation?
       - 1.0 = Perfect, all source fields useful for CV
       - 0.5 = Some irrelevant fields
       - 0.0 = Source data not useful
    
    2. answer_relevancy (0-1): Is the CV relevant to the source data?
       - 1.0 = CV perfectly matches source data scope
       - 0.5 = Some CV sections not grounded in source
       - 0.0 = CV unrelated to source
    
    3. faithfulness (0-1): Does CV only contain info from source (no hallucinations)?
       - 1.0 = Zero hallucinations, all facts from source
       - 0.5 = Minor inferences (e.g., "Fluent English" not in source)
       - 0.0 = Major hallucinations
    
    4. completeness (0-1): Does CV include all critical source info?
       - 1.0 = All work history, skills, education included
       - 0.5 = Missing some important details
       - 0.0 = Major omissions
    
    5. overall_score (0-10): Holistic quality for employer use
    
    Be strict and objective. Penalize hallucinations heavily."""
    
    user_prompt = f"""Evaluate this CV generation:
    
SOURCE DATA:
{json.dumps(source_data, indent=2)}

GENERATED CV:
{json.dumps(generated_cv, indent=2)}

Return evaluation metrics with detailed reasoning."""
    
    try:
        response = get_llm_response(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0.1,  # Low temperature for consistent evaluation
            model=get_model_for_task("cv_review"),  # Use high-quality model
            response_model=EvaluationMetrics
        )
        return response.parsed
    except Exception as e:
        print(f"Evaluation failed: {e}")
        # Return default low scores on failure
        return EvaluationMetrics(
            context_relevancy=0.0,
            answer_relevancy=0.0,
            faithfulness=0.0,
            completeness=0.0,
            overall_score=0.0,
            reasoning=f"Evaluation error: {str(e)}"
        )


def run_ragas_evaluation(num_samples: int = 5) -> RAGASEvaluationReport:
    """
    Run full RAGAS evaluation on multiple CV generations.
    
    Args:
        num_samples: Number of employee records to evaluate
    
    Returns:
        RAGASEvaluationReport with aggregated metrics
    """
    print(f"🔍 Running RAGAS evaluation on {num_samples} samples...")
    
    # Load and index employee data
    records = merge_records_on_the_fly()
    build_index(records)
    
    # Select sample records
    sample_records = records[:num_samples]
    
    # Generate CVs and evaluate
    evaluations = []
    drafting_agent = DraftingAgent()
    
    for i, record in enumerate(sample_records, 1):
        print(f"\n📄 Evaluating CV {i}/{num_samples}: {record.get('full_name', 'Unknown')}")
        
        # Generate CV
        draft = drafting_agent.generate(record)
        
        # Evaluate
        metrics = evaluate_cv_with_ragas(record, draft["cv"])
        evaluations.append(metrics)
        
        print(f"  ✓ Faithfulness: {metrics.faithfulness:.2f}")
        print(f"  ✓ Completeness: {metrics.completeness:.2f}")
        print(f"  ✓ Overall: {metrics.overall_score:.1f}/10")
    
    # Calculate averages
    avg_context = sum(e.context_relevancy for e in evaluations) / len(evaluations)
    avg_answer = sum(e.answer_relevancy for e in evaluations) / len(evaluations)
    avg_faith = sum(e.faithfulness for e in evaluations) / len(evaluations)
    avg_complete = sum(e.completeness for e in evaluations) / len(evaluations)
    avg_overall = sum(e.overall_score for e in evaluations) / len(evaluations)
    
    report = RAGASEvaluationReport(
        evaluations=evaluations,
        average_context_relevancy=avg_context,
        average_answer_relevancy=avg_answer,
        average_faithfulness=avg_faith,
        average_completeness=avg_complete,
        average_overall_score=avg_overall
    )
    
    print(f"\n{'='*60}")
    print(f"📊 RAGAS EVALUATION SUMMARY")
    print(f"{'='*60}")
    print(f"Average Context Relevancy:  {avg_context:.2f}")
    print(f"Average Answer Relevancy:   {avg_answer:.2f}")
    print(f"Average Faithfulness:       {avg_faith:.2f}")
    print(f"Average Completeness:       {avg_complete:.2f}")
    print(f"Average Overall Score:      {avg_overall:.1f}/10")
    print(f"{'='*60}\n")
    
    return report


if __name__ == "__main__":
    import sys
    
    num_samples = int(sys.argv[1]) if len(sys.argv) > 1 else 5
    
    report = run_ragas_evaluation(num_samples)
    
    # Save report
    output_file = "ragas_evaluation_report.json"
    with open(output_file, "w") as f:
        json.dump(report.model_dump(), f, indent=2)
    
    print(f"✅ Full report saved to: {output_file}")
